import "$styles/index.css"
import "$styles/syntax-highlighting.css"

// Import all JavaScript & CSS files from src/_components
import components from "$components/**/*.{js,jsx,js.rb,css}"

import "./landing.js"
import "./breadcrumb.js"
import "./hamburger-menu.js"
import "./announcement-banner.js"
import "./progress.js"
import "./memory-verse-audio.js"
import "./page-speak.js"
import "./journal.js"
import "./journal-print.js"
import "./settings.js"
import "./group-share.js"
import "./contact.js"
import "./discussions.js"
import "./search.js"
